### PR TITLE
[FIX] test: refactor project test.

### LINKED ISSUE #21: Review project test
The test should be refactor, in other case it will not be usefull

### PR DESCRIPTION
**Pull request by bim-g**
Fix problem test, due to the refactoring all test failed.
closes #21

### CODE REVIEW

File: test/MetaDataTest.php [hunk 1]
```diff
@@ -143,23 +180,23 @@ function testMetaHTMLMedataDataStructure()
         /**
          * check expectation
          */
-        $this->assertNotEquals($metaExpex, $meta);
+        $this->assertNotEquals($metaExpectation, $meta);
     }
-    function testNotMetaHTMLMedataDataStructure()
+    function testNotHTMLMedataDataStructure()
```
Comment (bim-g) [inline test/MetaDataTest.php:185]: This one was missing
